server {
    listen 443 ssl;
    server_name localhost;
    ssl_certificate /etc/ssl/certs/devops.crt;
    ssl_certificate_key /etc/ssl/private/devops.key;
    location / {
        add_header X-Powered-By "DevOps-Toolkit";
        return 200 "DevOps Toolkit Build 2 is Live!\n";
    }
}
